name: whitecodel_reels
description: "A Flutter package to easily integrate instagram like reels in your app"
version: 0.0.6
homepage: https://github.com/whitecodel/whitecodel_reels

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  get: ^4.7.2
  video_player: ^2.9.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0